version: "3.9"
services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - php-apache
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
    networks:
      - default
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.php-apache.schedule: "@every 1m"
      ofelia.job-exec.php-apache.command: "php /var/www/html/src/check_codicetemp.php"

  database:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: WkG7vqWUF65W9o!z
      MYSQL_DATABASE: centro_diagnostica
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    build: './build/phpmyadmin'
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 128M
    volumes:
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - default

networks:
  default:
    external: false
